name: Laravel CI

on:
  push:
    branches:
      - staging
      - main

  pull_request:
    branches:
      - staging
      - main


jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: bookingflow
          MYSQL_USER: bookingflow
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, mysql, pdo_mysql
          coverage: none


      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress


      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate


      - name: Run migrations
        run: php artisan migrate --force --seed
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: bookingflow
          DB_USERNAME: bookingflow
          DB_PASSWORD: secret


      - name: Run Laravel Pint
        run: ./vendor/bin/pint


      - name: Run Tests
        run: php artisan test
